name: detect affected packages
on: 
  push: 
    branches: [ main ]

jobs: 
  detect-affected:
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.changes.outputs.affected }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Get changed packages
        id: changes
        run: |
          python .github/detect_affected.py "${{ github.event.before }}" "${{ github.sha }}" 2>>$GITHUB_OUTPUT
  do-something:
    needs: detect-affected
    strategy:
      matrix:
        crate: ${{ fromJSON(needs.detect-affected.outputs.affected) }}
    uses: ./.github/workflows/do-something-with-affected-crate.yaml
    with:
      crate: ${{ matrix.crate }}
        
